### PR TITLE
resolves #4 generate permutations

### LINKED ISSUE #4: Gen.permute
After playing with this for a while, it works, but it's not giving me exactly what i wanted.  I was hoping for more of a permutation based generator. Say i have
`Gen.pojo(X,  a : Gen.these(1,2), b : Gen.these(3,4))`

realizing this list gives (excuse my json notation) me `[{a : 1, b:3}, {a:2, b:4}]`.   But what i wanted was  `[{a : 1, b:3}, {a : 1, b:4}, {a : 2, b:3}, {a:2, b:4}]`.  this gets more interesting if you use it against a graph, like:

```
Gen.pojo(A,  
  def bGen = Gen.pojo(B,
      b1 : Gen.these(null, 1)
  )

  def bGenInifite = bGen.repeat
  //Non null can just be infinite,  different generator will terminate this
  a1 : Gen.integer, 

  //collections most interesting values are null, empty, 1 item, 2+ items
  a2 : Gen.these(null, [])
    //every permutation of 1 item
    .then bGen.map { [it] }
     //fyi groovy's CrossJoin/pair stuff escapes me at this moment)
    .then bGen.crossJoin( bGen).map( {[it.left, it.right]} )
```

that gives you quite the set of permutations.  Beyond that something like these rules could be built with a reflection factory.  

So kinda a depth first generator off of the rules.

I'm considering putting one together as i have a lot of transformers in my code pipeline that'd i'd be interesting in sending different permutations of my POJO's through just to make sure they don't crash.

It fails to account for relationships between properties. IE Maybe a2 cannot b null if a1 is odd.  Taking it another evolution, you could have a ContextGenerator that get's the currently constructed tree as it moves through the tree, so each generator could decided based upon the current tree.  In that case offering depth and bredth first generators would allow people to construct semantic pojo's for most scenarios.  IE the a1 gen would get an instance of A passed in that already has a2 filled in..or reverse and execute the delegate for the next.

just kinda spitballing here to see if it clicks with anything you've been thinking about.

### PR DESCRIPTION
**Pull request by Bijnagte**
This is still a work in progress. It needs expansion to include permutations for defined Map and Pojo generators. Those can be built on top of the tuple generator though. This is also only depth first. There also would need to be docs and the permute method added to the relevent classes. I think it should target the 0.6 version because of the remaining work.
@drdamour

cc @mariogarcia

### CODE REVIEW

File: src/main/groovy/spock/genesis/generators/composites/PermutationGenerator.groovy [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+        new UnmodifiableIterator<List<E>>() {
+            private final List<List<E>> emitted = []
+            private final List<List<E>> currentEmmited = []
+            private int column = 0
+            private E value
+            private Iterator<List<E>> emittedIterator
+
+            @Override
+            boolean hasNext() {
+                if (emitted == []) {
```
Comment (mariogarcia) [inline src/main/groovy/spock/genesis/generators/composites/PermutationGenerator.groovy]: In order to keep symmetry with line `61` and still using idiomatic Groovy, I would have used `!emmited`.

Comment (Bijnagte) [inline src/main/groovy/spock/genesis/generators/composites/PermutationGenerator.groovy]: good call, I will update

File: src/main/groovy/spock/genesis/generators/composites/PermutationGenerator.groovy [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+    PermutationGenerator(List<Generator<E>> generators, int maxDepth) {
+        super(generators)
+        this.maxDepth = maxDepth
+    }
+
+    PermutationGenerator(List<Generator<E>> generators) {
+        super(generators)
+        this.maxDepth = pickMaxDepth(generators)
+    }
```
Comment (mariogarcia) [inline src/main/groovy/spock/genesis/generators/composites/PermutationGenerator.groovy:21]: Change

``` groovy
 PermutationGenerator(List<Generator<E>> generators) {
         super(generators)
         this.maxDepth = pickMaxDepth(generators)
 }
```

to

``` groovy
 PermutationGenerator(List<Generator<E>> generators) {
         this(generators, pickMaxDepth(generators))
 }
```

Then you will be reusing `PermutationGenerator(List<Generator<E>> generators, int maxDepth)`, which at the moment was not covered by any test. From now on it will :)

**Comment by mariogarcia** [comment]
Added some minor comments @Bijnagte

**Comment by Bijnagte** [comment]
I will hold off on pushing those updates until I have the permutations for Maps working too. Thanks again for reviewing all of this!

**Comment by mariogarcia** [comment]
:+1:

**Comment by Bijnagte** [comment]
I think that is everything for this issue now except docs
